### ISSUE TITLE
Changes made on  https://developer.husqvarnagroup.cloud/

### ISSUE THREAD

**Issue by sabbatho** [py-smart-gardena/hass-gardena-smart-system#115]
Hi,
Not sure about changes that seem to have been made to the developer portal.
I have to add an redirect url, but i'm not sure what to put there? Guess this needs to be added to the documentation aswell?

![bild](https://user-images.githubusercontent.com/48513738/173013597-dc7e76f6-15bf-4fba-89de-98933f9d7be2.png)

As they must have done changes late yesterday, i couldn't log in until today and my application was removed. So i had no choice but to create a new one :(

Anyone with a suggestion on what to add as the redirect url?
Also i had not upgraded from 0.2.5b4 when this happened, and have been using 0.2.5b4 for a long time with no issues.

Thanks in advance

//Jimmy

**Comment by RobG80** [comment]
I join the question. The integration does not work

**Comment by EvertJob** [comment]
Yep. Here another user that has this issue.

**Comment by AquaWolf** [comment]
Seems like grant_type that is used is not supported anymore.
Another grant flow should be used here
https://github.com/grm/py-smart-gardena/blob/026f32c184341d3c807797ddcaa05a69c84ffadb/src/gardena/smart_system.py#L96

Husqvarna suggests the client credentials grant flow
Client secret and id is then used to get an access token:
https://developer.husqvarnagroup.cloud/docs/api#client-credentials-grant
Here is the documentation for the used oauth lib
https://github.com/requests/requests-oauthlib/blob/master/docs/oauth2_workflow.rst#id12

This it the same issue like #114

**Comment by AquaWolf** [comment]
I added an issue in the py_smart_garden repo:
https://github.com/py-smart-gardena/py-smart-gardena/issues/136

**Comment by grm** [comment]
Hey !

thx for the report, it seems husqvarna changed solently their API ((not the first time :( ).
They suck at communication :)

Btw, i will try to correct this issue by the end of the week end, as i have some improvments regarding http library being currently in use (i changed the library that was having issue by a new async one).
This changes are already integrated in 1.0.0b5, but as gardena just change the authentication method, you cannot test it yet !

Btw, thx for the feedback

**Comment by sabbatho** [comment]
Either the Core crew had done something they fixed in 2022.6.5, or Husqvarna changed back, because after installing 2022.6.5 and restarting it's now working again.
no update done with anything else in hacs or addon.

and i have not logged in to Husqvarna dev-site and added a new application.

Someone else that can confirm? or am i going mad? :)

**Comment by RobG80** [comment]
exactly yes after upgrade to 2022.6.5 it came back

**Comment by EvertJob** [comment]
My guess is that Husqvarna changed the API because my 'old' key is visible where a few days ago it wasn't listed.

**Comment by AquaWolf** [comment]
I deleted the integration yesterday and when trying to get an access token I still get the grant_type error

**Comment by grm** [comment]
Hello,

indeed, I had the same issue.
I think they have either rollback to a previous versitn (not sure why) or maybe all their servers are not updated at the same time, and depending on the server you are using, you may have not the same version 

But the client credentials flow is the way of the story and more adapted to our use case.

I juste released a beta version of 1.0.0b900 which should include all new functionalities and use the new credentials information so you have to deconfigure and reconfigure the integration. I have still display bug during configuration to solve, but everything seems to work as intended.

Please tell me if you have any issue

**Comment by sabbatho** [comment]
Works perfectly for me!
Thanks for all your work @grm 

Just needed to delete the integration after i had updated with hacs. find the application key and secret key (they were still there in the husqvarna dev-portal, just copied the existing ones. all good!

//Jimmy

**Comment by sabbatho** [comment]
We'll see what will happen with that redirect url they asked for briefly, but as of now i'd say case closed :)

Thanks again!

//Jimmy

**Comment by tlender** [comment]
Hello, I'm new here and I'm also having the same URL problem. Version V0.2.3 is installed. I need help, whether I have installed the correct version and which URL to enter on the husqvarnagroup site? Please give a little info, thank you!

**Comment by tlender** [comment]
Hi @sabbatho, thanks a lot, it works, graet job! :-)
