### ISSUE TITLE
Error with latest v0.2.3 in HA 2021.6.0

### ISSUE THREAD

**Issue by newlund** [py-smart-gardena/hass-gardena-smart-system#68]
Getting this error with latest v0.2.3 in HA 2021.6.0

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:88
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 19:04:42 (1 occurrences)
Last logged: 19:04:42

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MikeLehnitz** [comment]
II have the same problem

**Comment by brlnr23** [comment]
same here. I think this addon is simply dead. Sad but true :/

**Comment by grm** [comment]
Hello ! The addon is not dead. I probably made an issue while releasing the
new version..
I am currenty trying to figure what and i will release a new versiln soon !


Le ven. 4 juin 2021 à 19:45, Chris Lange ***@***.***> a
écrit :

**Comment by grm** [comment]
I just released a new 0.2.3 version in beta. Could you try uninstall and reinstall the new one ?
I am currently running Home Assistant 2021.6.1 and it seems to work from my first tests.

**Comment by brlnr23** [comment]
Sorry, I was referring to the badge seen in HA which states "unmainted as of 2020". But happy to hear, that the development is still ongoing! Thanks for your efforts!

I did an upgrade to the new beta and I can confirm that it's working again!
HA 2021.6.1

Thanks a lot for your quick reaction!

**Comment by grm** [comment]
Good to know :)
I updated the badge after the last failing release !
I will close this ticket. Do not hesitate to repoen it if it is still failing !

Jérémie

**Comment by newlund** [comment]
I'm still getting the same error. I have removed everything and reinstalled the latest 0.2.3.
When I enter email, pw, and app id I get this in the logs.

This error originated from a custom integration.

Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:133
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 10:40:19 (1 occurrences)
Last logged: 10:40:19

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
